### ISSUE TITLE
超时

### ISSUE THREAD

**Issue by kistonw** [xiaoxx970/chatgpt-in-terminal#10]
返回这个提示Error: API read timed out (20s). You can retry or increase the timeout.

**Comment by Ace-Radom** [comment]
这个是因为GPT超过预设的20秒时间限制后还没有回复 为了避免假死而停止等待直接结束和ChatGPT的通信
改变超时时间设置可以在 `.env` 文件内加上 `OPENAI_API_TIMEOUT` 设置 或者在启动后使用 `/timeout` 命令更改超时时长设置

例如在 `.env` 内：
```
OPENAI_API_KEY=sk-xxxx
OPENAI_API_TIMEOUT=40
```
或者在启动后使用命令：
```
/timeout 40
```
这两种方法都可以将超时时长改为40秒 但区别是 `.env` 内的设置是一劳永逸的 但使用 `/timeout` 命令更改的超时时长会在重启后重置
