### ISSUE TITLE
gen_title函数的linux兼容性错误；title自动生成和CLI标题更改

### ISSUE THREAD

**Issue by Ace-Radom** [xiaoxx970/chatgpt-in-terminal#17]
在 `gen_title` 函数加入后在个人windows端上可以正常使用 但在WSL内的linux环境中却在启动时报错
```
Traceback (most recent call last):
  File "/mnt/e/forks/chatgpt-in-terminal/chat.py", line 74, in <module>
    class ChatGPT:
  File "/mnt/e/forks/chatgpt-in-terminal/chat.py", line 210, in ChatGPT
    def gen_title(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
尚不清楚这种错误是因为python版本导致还是linux环境导致 mac的话因为我手头没有mac设备所以没法测试

个人系统环境：
- Windows 11
- - cPython 3.10.8
- Windows Subsystem for Linux
- - Debian 11.6 (Subsystem v1.14.0.0)
- - - cPython 3.9.2

另外我在尝试在一次chat中的第一次conversation完成后分离一个线程出来生成标题 生成成功后更改终端的标题
目前更改标题的函数在windows和WSL上测试过了 但我还没写太多 你看到了之后要不考虑一下要不要加入这个功能

**Comment by xiaoxx970** [comment]
> 另外我在尝试在一次chat中的第一次conversation完成后分离一个线程出来生成标题 生成成功后更改终端的标题
目前更改标题的函数在windows和WSL上测试过了 但我还没写太多 你看到了之后要不考虑一下要不要加入这个功能

这个功能挺好，我也想过这么做的但是感觉会很复杂就没去弄，你可以试试

> 在 gen_title 函数加入后在个人windows端上可以正常使用 但在WSL内的linux环境中却在启动时报错

这个的话我又查了下好像这样定义返回类型确实不符合python的语法，应该用Union[str, None]，稍后更新

**Comment by Ace-Radom** [comment]
好的 那我同步一下分支继续往下写了
