### ISSUE TITLE
单方面宣布，这是目前最好的terminal chatgpt

### ISSUE THREAD

**Issue by MichaelC001** [xiaoxx970/chatgpt-in-terminal#19]

**Comment by MichaelC001** [comment]
第二好用的是 https://github.com/sigoden/aichat 
rust 确实快

**Comment by MichaelC001** [comment]
旧版本我更改以下字段后面的内容自定义prompt，保存多个程序，不同程序使用不同prompt。但是新版本代码好复杂，请问怎么自定义prompt，更改哪里啊？ system prompt是什么意思，是default prompt？
 
self.messages = [
            {"role": "system", "content": "

**Comment by Ace-Radom** [comment]
~半开发者碎碎念~
性能问题可能真的没啥办法 启动确实是要一两秒 但要达到这样的界面还要保证~开发难度不飞天~确实能力范围内只能python了【当然了我就一个交pr的项目底层我也不敢动】
曾经考虑过用C重构整个项目 但C的CLI库实在是一言难尽 不是不好用 是跨平台太麻烦 而且要做到这样漂亮的界面时间成本和难度是指数级增长 实在是没那个精力
另外你删掉的一个comment里有提到代码复杂的问题 这个……老实说我在B站上看到这个项目然后来交pr的时候代码远没有现在这样 但现在这个情况就是在一个源文件里加入了太多太多的功能导致说实话 源码已经是有点臃肿和混乱了 如果我现在是第一次看这个源码可能要花很多时间才能看懂【其实我现在在扩展功能的时候也有点吃力 代码太长了】
虽然 @xiaoxx970 owner本人有做过一定的清理但目前的情况就是很难在不打散很多功能的情况下简化了 本来我在交前几个PR的时候就有考虑过把程序拆成多个文件但最后考虑到毕竟我不是这个项目的发起者充其量只是一个贡献者 动底层规划这种还是owner考虑吧

~说实话当初在B站看到这个项目的时候就觉得潜力很大 但没想到结果真能弄成现在这样~

**Comment by xiaoxx970** [comment]
> 旧版本我更改以下字段后面的内容自定义prompt，保存多个程序，不同程序使用不同prompt

现在有更好的办法了噢，首先/system更改系统prompt，然后/save保存会话(没有聊天内容只有系统prompt的会话)，根据用途命名json文件。下次要用的时候通过--load命令加载不同的会话，就能达到效果啦

**Comment by xiaoxx970** [comment]
> 动底层规划这种还是owner考虑吧

确实有考虑分到多个文件，当时还问过ChatGPT我这个代码该不该分，它说还行也不是很多。现在的话应该是接近这个临界点了，但是分的话它就不是一个可以拿着到处复制的单个py文件了，我也不知道一个Python项目需不需要这种便携性。所以这个可以再讨论讨论

**Comment by Ace-Radom** [comment]
> 现在的话应该是接近这个临界点了，但是分的话它就不是一个可以拿着到处复制的单个py文件了，我也不知道一个Python项目需不需要这种便携性。

嘛……我因为没有什么py的开发经验 但根据曾今参加的那些C和C++项目给我的理解就是 “你是把这个项目当成一个工具还是一个软件来开发的”
也就是 如果这是一个软件的话 那我就会把所有轮子全部编译成dll 因为这种情况下我不会太过考虑安装文件夹的文件是否太多
但如果他是一个工具 那我可能就会选择全部静态链接出来一个毫无依赖的exe 因为这样可以保证这个工具的便携性
总之我的意思就是你认为这个项目是一个“软件”还是一个“工具”的问题

**Comment by xiaoxx970** [comment]
那还是工具我觉得。而且比起分成多个文件，我更多是想简化代码，比如去掉一些冗余的逻辑，尽可能多的复用函数，甚至减少一些功能
