### ISSUE TITLE
在stream模式下让用户选择显示模式

### ISSUE THREAD

**Issue by xiaoxx970** [xiaoxx970/chatgpt-in-terminal#21]
https://rich.readthedocs.io/en/latest/live.html#vertical-overflow

当前是使用默认的ellipsis模式，当生成内容超出屏幕的时候，会在最下方显示三个小点，等所有内容生成完成的时候会一次性显示出剩余内容。这个模式在内容少的时候还好，如果内容很多，那内容超出屏幕后用户又只剩下了等待，内容越长等待越久。

当时考虑使用另一种模式：visible，这个模式能持续的flow输出答案，内容超过窗口高度的时候就向下滚动输出。这个模式能很好的解决用户的等待问题，但是缺点就是，不能在这个时候滚动屏幕，否则屏幕将快速刷新，导致屏幕外的内容彻底失控，最后只能正确显示当前屏幕的内容。

但是现在我实际使用下来，发现如果内容太长，我还是愿意不滚动屏幕，然后选择visible模式，看着所有回答慢慢出现。所以稍后打算把这个模式的选择做成/stream的子命令

**Comment by xiaoxx970** [comment]
闲来无事来填坑了，我觉得用2.很好，马上弄一个

**Comment by Ace-Radom** [comment]
hm我不知道python的rich live是怎么实现的 没看过源码 但我自己在写的md渲染器的live就是靠ANSI擦除+覆写实现伪流式输出的 我估计python里的库优化肯定更多但应该大差不差
但这种……覆写就不可避免造成在文字坐标改变时候写错位:joy: 就看用户怎么用了

**Comment by xiaoxx970** [comment]
是的估计终端下rich只能做到这样了
