### ISSUE TITLE
请问可以自定义prompt吗？

### ISSUE THREAD

**Issue by MichaelC001** [xiaoxx970/chatgpt-in-terminal#3]
请问可以自定义prompt吗？

**Comment by xiaoxx970** [comment]
你是说系统prompt吗？目前还不能自定义，但是可以直接在[代码](https://github.com/xiaoxx970/chatgpt-in-terminal/blob/main/chat.py#L31)里修改

**Comment by MichaelC001** [comment]
> 你是说系统prompt吗？目前还不能自定义，但是可以直接在[代码](https://github.com/xiaoxx970/chatgpt-in-terminal/blob/main/chat.py#L31)里修改

搞定了，非常好用，希望继续更新

**Comment by xiaoxx970** [comment]
新版本支持定义系统prompt啦
