### ISSUE TITLE
pip3 安装后如何启动

### ISSUE THREAD

**Issue by Nuyoahzsp** [xiaoxx970/chatgpt-in-terminal#38]
在zsh终端中pip3下载安装好后，找不到gpt-term这个命令。或者还要配下环境变量？

**Comment by xiaoxx970** [comment]
pip显示安装成功了吗？一般可能要退出终端重新打开才生效。你可以运行这个命令查看是否成功安装
```sh
pip3 show gpt-term
```

**Comment by Nuyoahzsp** [comment]
Nuyoahz-MBP 19:03 ~ pip3 show gpt-term 
Name: gpt-term
Version: 1.0.4
Summary: Use ChatGPT in terminal
Home-page: https://github.com/xiaoxx970/chatgpt-in-terminal
Author: xiaoxx970
Author-email: 
License: MIT
Location: /Users/aling/Library/Python/3.9/lib/python/site-packages
Requires: requests, prompt-toolkit, rich, pyperclip, packaging, tiktoken, sseclient-py
Required-by: 
Nuyoahz-MBP 19:03 ~ gpt-term
zsh: command not found: gpt-term

已重启终端/重启系统

**Comment by xiaoxx970** [comment]
可能是要设置环境变量，你用的是mac系统自带的python吧，推荐使用homebrew安装的python这样它能帮你处理环境变量的问题，不然的话你就得找找如何为mac自带pip装的包配置环境变量

**Comment by Nuyoahzsp** [comment]
我的python 用的是3.8，配的环境也是3.8，用brew装的

**Comment by Ace-Radom** [comment]
这个问题应该在mac下和linux下都会出现【我的测试环境是winpowershell和WSL+zsh】
你需要把pip的包安装文件夹加到环境变量里 如果是linux的话需要在 `~/.zshrc` 里加上一句
```
export PATH=$PATH:~/.local/bin
```
我不知道mac是否一样

**Comment by xiaoxx970** [comment]
可以参考这里说的path添加到path: https://github.com/jupyter/help/issues/89#issuecomment-252254703

**Comment by xiaoxx970** [comment]
> 我的python 用的是3.8，配的环境也是3.8，用brew装的python 3.8

还有根据你的输出信息的话你用的应该还是mac自带的python和pip，我自己输出看的话能看到homebrew的路径：
```sh
Name: gpt-term
Version: 1.0.4
Summary: Use ChatGPT in terminal
Home-page: https://github.com/xiaoxx970/chatgpt-in-terminal
Author: xiaoxx970
Author-email:
License: MIT
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: packaging, prompt-toolkit, pyperclip, requests, rich, sseclient-py, tiktoken
Required-by:
```

你还可以通过 `pip3 -V` 和 `which python3` 查看你的python位置

**Comment by Nuyoahzsp** [comment]
解决了，我以前卸载了mac自带的2.7的，然后不知道从哪里给我下了个3.9的。把3.9的卸载后重新用3.8的pip下载安装后，就可以成功启动了，本质还是环境变量问题。然后mac自己下的3.9启动会报错
```shell
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
```

**Comment by xiaoxx970** [comment]
好的那我就关闭issue了
