### ISSUE TITLE
能否支持渲染latex公式

### ISSUE THREAD

**Issue by justcyl** [xiaoxx970/chatgpt-in-terminal#4]
希望能对markdown中的数学公式进行渲染

**Comment by xiaoxx970** [comment]
由于调用的库([rich](https://github.com/Textualize/rich))不支持在markdown中渲染LaTeX，所以我的代码大概率也不会支持，但是你可以让GPT输出 unicode 格式的数学公式
<img width="463" alt="image" src="https://user-images.githubusercontent.com/28559039/226272650-83791293-338a-476f-aeff-683ddbe0d859.png">
