### ISSUE TITLE
不知道原因 看看谁知道帮忙解决一下

### ISSUE THREAD

**Issue by demond2633** [xiaoxx970/chatgpt-in-terminal#40]
我是放在了linux里环境里 运行代码时 出现了错误 见图
![微信截图_20230517154359](https://github.com/xiaoxx970/chatgpt-in-terminal/assets/31739013/af534779-4ffb-4076-a4a1-c05f4f99da08)

**Comment by xiaoxx970** [comment]
看看你的 tiktoken 的版本是多少
我的是0.3.3
```
Name: tiktoken
Version: 0.3.3
Summary: tiktoken is a fast BPE tokeniser for use with OpenAI's models
Home-page: 
Author: Shantanu Jain
Author-email: shantanu@openai.com
License: MIT License
```

**Comment by xiaoxx970** [comment]
因为你一直没回复我就先关掉这个issuse了，有问题欢迎继续提问

**Comment by demond2633** [comment]
我的tiktoken显示正常啊
<img width="587" alt="微信图片_20230521190741" src="https://github.com/xiaoxx970/chatgpt-in-terminal/assets/31739013/65601bfe-c13e-42d7-b226-b94c3d7168ff">

**Comment by xiaoxx970** [comment]
看上去没问题，只有在运行 `python chat.py` 的时候才会报错吗还是通过pip安装的 gpt-term 运行也报错？

**Comment by demond2633** [comment]
是运行的时候就报错~

**Comment by demond2633** [comment]
顺便说一下 这个tiktoken库 我是从我另一个win系统的电脑里考到linux的 因为正常安装这个库 会有一部分安装不上 报错 请见图
<img width="822" alt="微信图片_20230521193109" src="https://github.com/xiaoxx970/chatgpt-in-terminal/assets/31739013/fe414f9c-6f87-4fb4-924c-14e01b84f7e1">

**Comment by xiaoxx970** [comment]
> 顺便说一下 这个tiktoken库 我是从我另一个win系统的电脑里考到linux的 因为正常安装这个库 会有一部分安装不上 报错 请见图 <img alt="微信图片_20230521193109" width="822" src="https://user-images.githubusercontent.com/31739013/239737874-fe414f9c-6f87-4fb4-924c-14e01b84f7e1.png">

搜了下这个错误是因为rust版本需要更新的原因：https://stackoverflow.com/questions/74697023/how-to-fix-this-version-of-cargo-is-older-than-the-2021-edition-error

你可以按照里面的前往 https://rustup.rs/ 运行安装脚本试试

还有你拷贝的是arm版本的whl安装包还是什么

**Comment by Ace-Radom** [comment]
> 顺便说一下 这个tiktoken库 我是从我另一个win系统的电脑里考到linux的 因为正常安装这个库 会有一部分安装不上

同上 建议看一下rust版本 tiktoken底层并不是py写的而是rust 出现build错误大概率是rust出了问题

**Comment by demond2633** [comment]
解决了 是rust问题 但我之前的rust也安装不上 我把32位改成64位就可以了~
