### ISSUE TITLE
请教一下，怎么使用这个软件作为API？

### ISSUE THREAD

**Issue by MichaelC001** [xiaoxx970/chatgpt-in-terminal#42]
这个软件很好用，不用需要每次进入软件的界面。能不能实现在别的地方输入或者选中一句话，作为变量，在这个软件里面问chatgpt，再把答案输出返回到剪贴板或者某个变量里面。谢谢

**Comment by Ace-Radom** [comment]
理论上自然是可以实现的 比如你从别处拷贝一句话 然后在gpt-term里用命令读取剪切板发送 回复覆写剪切板
是否加入实现可以探讨一下

**Comment by xiaoxx970** [comment]
> 这个软件很好用，不用需要每次进入软件的界面。能不能实现在别的地方输入或者选中一句话，作为变量，在这个软件里面问chatgpt，再把答案输出返回到剪贴板或者某个变量里面。谢谢

你想说的是不是通过参数来提问，比如
```shell
gpt-term 今天天气怎么样
```
然后不需要进入程序，直接返回 ChatGPT 的回答，或者再复制到剪贴板
然后这样就可以把回答放到变量里面
```shell
answer=$(gpt-term 今天天气怎么样)
```
或者
```shell
gpt-term 今天天气怎么样 | read answer
```

**Comment by MichaelC001** [comment]
> ```shell
> gpt-term 今天天气怎么样
> ```

运行这个会显示 没有"今天天气怎么样"这样的参数

**Comment by xiaoxx970** [comment]
昂还没做呢你不是一直没回吗，觉得这个功能需要的话我们可以做下
________________________________
发件人: MichaelC001 ***@***.***>
发送时间: Tuesday, June 20, 2023 7:38:14 PM
收件人: xiaoxx970/chatgpt-in-terminal ***@***.***>
抄送: xiaoxx970 ***@***.***>; Assign ***@***.***>
主题: Re: [xiaoxx970/chatgpt-in-terminal] 请教一下，怎么使用这个软件作为API？ (Issue #42)


gpt-term 今天天气怎么样

运行这个会显示 没有"今天天气怎么样"这样的参数

―

**Comment by xiaoxx970** [comment]
相关issuse： #60
