### ISSUE TITLE
POST地址错误

### ISSUE THREAD

**Issue by PixelChen24** [xiaoxx970/chatgpt-in-terminal#5]
运行`chat.py`输入问题后，会遇到错误:
```shell
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)
```
我用的openai版本是0.27.2

**Comment by xiaoxx970** [comment]
可以提供下完整的trace信息吗，那样更容易定位一点。其次是要确保你的终端能正常使用代理，国内网络是无法使用的，尝试运行 `nslookup api.openai.com` 看解析出来的是不是美国Microsoft的地址。
