### ISSUE TITLE
在token达到上限后再输入退出词退出时应该直接退出而不是询问是否删除最早消息

### ISSUE THREAD

**Issue by xiaoxx970** [xiaoxx970/chatgpt-in-terminal#54]
![image](https://github.com/xiaoxx970/chatgpt-in-terminal/assets/28559039/7d578387-693d-4e5c-9fa9-853b28d61766)

如图，其实可以考虑不要提示删除这个功能，只要警告，等openai返回400错误后再提示也不迟

**Comment by Ace-Radom** [comment]
<img width="704" alt="image" src="https://github.com/xiaoxx970/chatgpt-in-terminal/assets/104905842/247104ad-8875-447c-b1c0-bd4df478b12f">
有 但不是全部都显示不出来 并且这个问题只在原生powershell上出现 原生cmd上没有
估计是老win终端的颜色适配问题吧 像dim之类的一样显示不出来

**Comment by xiaoxx970** [comment]
可以可以，正好在1.1.3修复了这个问题
