### ISSUE TITLE
请问如何在terminal中直接返回答案？

### ISSUE THREAD

**Issue by MichaelC001** [xiaoxx970/chatgpt-in-terminal#58]
临时要问gpt一个问题，而不是连续对话，希望能在shell中直接问一个问题，gpt返回答案，后面可以接着在shell中工作，不用先进入gpt-term的python 程序，问完问题再退出。谢谢

**Comment by xiaoxx970** [comment]
如果想要将回答直接复制到剪贴板，mac下可以使用 `pbcopy` 命令来复制

```sh
gpt-term hi | pbcopy
``` 

此时再粘贴就是回答的内容
