### ISSUE TITLE
What values does the --set-model parameter take?

### ISSUE THREAD

**Issue by paolosezart** [xiaoxx970/chatgpt-in-terminal#63]
How can I change the Open-ai model? There is no information anywhere about what values can be passed to the --set-model parameter.
How can I find out?

**Comment by Ace-Radom** [comment]
![image](https://github.com/xiaoxx970/chatgpt-in-terminal/assets/104905842/399882b8-3bfb-4393-b66b-054ed0a96467)

You can check them with `/model` slash command. These models are also available with `--set-model-parameter` argument.
